apiVersion: v1
kind: Service
metadata:
    name: "demok8-490e"
    labels:
        app: "demok8-490e"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "demok8-490e"