on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jafardockerdemo.azurecr.io
        username: ${{ secrets.acr_jafardockerdemo_username }}
        password: ${{ secrets.acr_jafardockerdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/dockerProj" -f  "dockerProj/Dockerfile" -t jafardockerdemo.azurecr.io/demok8:${{ github.sha }} --label dockerfile-path=dockerProj/Dockerfile
        docker push jafardockerdemo.azurecr.io/demok8:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demok8_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demok886b9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demok886b9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demok886b9
        container-registry-url: jafardockerdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_jafardockerdemo_username }}
        container-registry-password: ${{ secrets.acr_jafardockerdemo_password }}
        secret-name: demok8dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demok886b9
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          jafardockerdemo.azurecr.io/demok8:${{ github.sha }}
        imagepullsecrets: |
          demok8dockerauth
